---
title: "Conference notes to ????"
author: 
  - name: Mária Kmety Barteková
    orcid: 0000-0003-2691-3185
format: gfm
editor: visual
---

These are the conference notes to xxxxxxx. (Please describe here the conference, add a link to the website, etc.)

## English version:

A well-managed culture (Bratislava 18.9.2023)

\- Strategy created without an action plan (without financial backing)

\- MK SR created to implement the strategy

\- Working groups created for individual areas

\- In the working. Groups experts from external environment + heads of departments at local governments + heads of culture departments from cities

\- 3 areas: law on culture, status of artist, law on sponsorship

\- Culture Act - naming of natural and legal persons

\- Status of the artist - a hot topic in both Portugal and the Czech Republic

\- The current leadership makes a recommendation to the future leadership of the Ministry of Culture of the Slovak Republic

Block: Objectives of cultural policy

Presentation - Marcel Čas

Measurable indicators are essential for assessing results

A clear objective of cultural policy - the creation, presentation, research and preservation of the arts, creative industries and cultural heritage resulting in a high quality and accessible artistic and cultural offer and positive socio-economic impacts of culture.

Best practice - Ministry of Health and their indicators

Social trust - the most important set of indicators

Culture and creative industries also have an impact on the economic development of the country

Two sets of indicators: trust in government and distrust in the media

Trust in government only 30%, we lag behind the EU average

Panel discussion: Marcel Čas, Jana Knežová, Zuzana Revešová, Marek Engeľ

M. Time - the data on the indicators are there, just nobody cared about them. They wanted indicators where they know the data already exists somewhere.

Cultural institutions were confused as to what they needed data for. It's about the principle of data collection. Set goals and directions and set indicators accordingly. It is about data literacy.

Reves - the best strategies are relatively participatory. Fear of misuse of data when collecting as part of CULT survey.

Culture is supposed to be a public good. Strategy creates a stable environment for culture.

Moderator.

There has been an investment contribution. This impulse brought about a change in thinking. Culture is not just a leisure activity, it has an educational benefit.

For financial indicators - using the Balance scorecard (4 dimensions)

Financial indicators

Professional indicators

PR-focused indicators

Indicators focused on internal processes

Monitoring - every 2 years

Best practice -- UK

Slovak version:

Dobre spravovaná kultúra (Bratislava 18.9.2023) 

·         Stratégia vytvorené bez akčného plánu (bez finančného krytia) 

·         MK SR vytvorilo implementáciu stratégie 

·         Vytvorené pracovné skupiny na jednotlivé oblasti 

·         V prac. skupinách experti z externého prostredia + vedúci oddelení na Samosprávach + vedúci oddelení kultúry z miest 

·         3 oblasti: zákon o kultúre, štatút umelca, zákon o sponzoringu 

·         Zákon o kultúre -- pomenovanie fyzických a právnických osôb 

·         Štatút umelca -- horúca téma aj v Portugalsku aj v ČR 

·         Aktuálne vedenie odovzdáva odporúčanie pre budúce vedenie MK SR 

**Blok: Ciele kultúrnej politiky**

**Prezentácia -- Marcel Čas**

Merateľné ukazovatele sú nevyhnutné pre hodnotenie výsledkov

Jednoznačný cieľ kultúrnej politiky -- tvorba, prezentácia, výskum a uchovávanie umenia, kreatívneho priemyslu a kultúrneho dedičstva, ktorých výsledkom je kvalitná a dostupná umelecká a kultúrna ponuka a pozitívne spoločensko-ekonomické dopady kultúry.

Best practise -- Ministerstvo zdravotníctva SR a ich indikátory

Spoločenská dôvera -- najdôležitejšia sada indikátorov

Kultúra a kreatívny priemysel majú dopad aj na ekonomický vývoj krajiny

Dve skupiny indikátorov: dôvera vo vládu a nedôvera v médiá

Dôvera vo vládu iba 30%, voči priemeru EÚ zaostávame

**Panelová diskusia: Marcel Čas, Jana Knežová, Zuzana Revešová, Marek Engeľ**

M. Čas -- dáta na indikátori sú, len sa o ne nikto nezaujímal. Chceli ukazovatele, kde vedia, že už dáta niekde existujú.

Kultúrne inštitúcie boli zmätené, že na čo treba dáta. Ide o princíp zbierania dát. Nataviť si ciele a smery a podľa toho nastaviť indikátory. Ide o dátovú gramotnosť.

Revešová -- najlepšie stratégie sú relatívne participatívne. Strach zo zneužitia dát pri zbere v rámci štatistického zisťovania KULT.

Kultúra má byť verejný statok. Stratégia vytvára stabilné prostredie pre kultúru.

Moderátor: Podarilo sa naplniť ciele Európskeho hlavného mesta kultúry -- Košice 2013?

Došlo k investičnému prínosu. Tento impulz priniesol zmenu myslenia. Kultúra nie je len voľnočasová aktivita, má edukačný prínos.

Pre finančné indikátory -- pomocou Balance scored card (4 dimenzie)

Finančné ukazovatele

Odborné ukazovatele

Ukazovatele zamerané na PR

Ukazovatele zamerané na interné procesy

Monitorovanie -- každé 2 roky

Best practise - UK
